# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: spa.utils.callbacks.EMAModelCheckpoint
  dirpath:      # directory to save the model file
  filename:      # checkpoint filename
  monitor:      # name of the logged metric which determines when model is improving
  verbose: false # verbosity mode
  save_last:      # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: 5 # save k best models (determined by above metric)
  mode: "min" # "max" means higher metric value is better, can be also "min"
  auto_insert_metric_name: true # when True, the checkpoints filenames will contain the metric name
  save_weights_only: false # if True, then only the modelâ€™s weights will be saved
  every_n_train_steps:      # number of training steps between checkpoints
  train_time_interval:      # checkpoints are monitored at the specified time interval
  every_n_epochs:      # number of epochs between checkpoints
  save_on_train_epoch_end:      # whether to run checkpointing at the end of the training epoch or the end of validation
